- name: Créer /root/.my.cnf pour accès root sans mot de passe
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user=root
      password={{ mariadb_root_password }}
    mode: '0600'

- name: Forcer le mot de passe root MariaDB + désactiver auth_socket
  command: >
    mariadb -e
    "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ mariadb_root_password }}'; FLUSH PRIVILEGES;"
  when: ansible_facts['os_family'] == "Debian"


- name: Définir l'authentification root en mysql_native_password (Ubuntu)
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mariadb_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    plugin: mysql_native_password
    state: present

- name: Créer la base de données WordPress
  community.mysql.mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mariadb_root_password }}"
