---
- name: Inclure installation des paquets
  include_tasks: install_packages.yml

- name: Configuration Apache et WordPress
  include_tasks: setup_wordpress.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Configuration MariaDB
  include_tasks: configure_mariadb.yml
  when: ansible_facts['os_family'] == 'Debian'
