- name: Télécharger WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
    mode: '0644'

- name: Décompresser WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
