---
- name: Restart Apache
  ansible.builtin.service:
    name: "{{ apache_service }}"
    state: restarted

- name: Restart MariaDB
  ansible.builtin.service:
    name: mariadb
    state: restarted



