---
- name: Créer un fichier vide sur tous les clients
  hosts: all
  gather_facts: false
  vars:
    nom_fichier: toto
  tasks:
    - name: Créer un fichier vide dans /tmp avec la variable nom_fichier
      ansible.builtin.file:
        path: "/tmp/{{ nom_fichier }}.log"
        state: touch
        mode: '0644'
