---
- name: Créer plusieurs utilisateurs sur tous les hôtes
  hosts: all
  become: yes

  vars:
    utilisateurs:
      - karim
      - sarah
      - louis

  tasks:
    - name: Créer les utilisateurs
      user:
        name: "{{ item }}"
        state: present
        create_home: yes
      loop: "{{ utilisateurs }}"
