---
- name: Installation de nginx selon la famille de l'OS
  hosts: all
  become: yes
  tasks:

    - name: Installer nginx avec apt (Debian/Ubuntu)
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Installer nginx avec yum (RedHat ou SUSE)
      yum:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Suse"
