---
- name: Désinstaller plusieurs paquets selon l'OS
  hosts: all
  become: yes

  vars:
    packages:
      - telnet
      - curl
      - wget

  tasks:
    - name: Désinstaller les paquets sur les systèmes Debian/Ubuntu
      apt:
        name: "{{ item }}"
        state: absent
        update_cache: yes
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == "Debian"

    - name: Désinstaller les paquets sur les systèmes RedHat/Rocky
      yum:
        name: "{{ item }}"
        state: absent
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == "RedHat"
